# Project information
site_name: NGUYEN Manh Hung
site_url: https://nmh4598.github.io/docs
site_author: NGUYEN Manh Hung
site_description: >-
  Write your documentation in Markdown and create a professional static site in
  minutes – searchable, customizable, in 60+ languages, for all devices


# Repository
repo_name: nmh4598.github.io
repo_url: https://github.com/nmh4598.github.io

# Copyright
copyright: |
  &copy; 2023 <a href="https://github.com/nmh4598"  target="_blank" rel="noopener">NGUYEN Manh Hung</a>

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - header.autohide
    # - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.view
    - content.action.edit
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: material/github

# Plugins
plugins:
  - social
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nmh4598
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/nmh4598/
    - icon: material/email
      link: mailto:nguyenmanhhung04051998@gmail.com

  blog:    
    author_image: https://avatars.githubusercontent.com/u/93479011
    words_read_per_minute: 300
    list_length: 25
    extended_preview: true

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Page tree
nav:
  - Home: index.md
  - Blog: 
    - Network analysis: blog/ana.md
    - Test: blog/test.md
    - Machine learning: blog/ml.md
  - About: about.md